window.esdocSearchIndex = [
  [
    "aureooms-js-fingertree/src/0-core/measure/cachedmeasure.js~cachedmeasure",
    "function/index.html#static-function-CachedMeasure",
    "<span>CachedMeasure</span> <span class=\"search-result-import-path\">aureooms-js-fingertree/src/0-core/measure/CachedMeasure.js</span>",
    "function"
  ],
  [
    "aureooms-js-fingertree/src/3-tree/implementations/2-deep.js~deep",
    "function/index.html#static-function-Deep",
    "<span>Deep</span> <span class=\"search-result-import-path\">aureooms-js-fingertree/src/3-tree/implementations/2-Deep.js</span>",
    "function"
  ],
  [
    "aureooms-js-fingertree/src/1-digit/0-digit.js~digit",
    "function/index.html#static-function-Digit",
    "<span>Digit</span> <span class=\"search-result-import-path\">aureooms-js-fingertree/src/1-digit/0-Digit.js</span>",
    "function"
  ],
  [
    "aureooms-js-fingertree/src/3-tree/implementations/0-empty.js~empty",
    "function/index.html#static-function-Empty",
    "<span>Empty</span> <span class=\"search-result-import-path\">aureooms-js-fingertree/src/3-tree/implementations/0-Empty.js</span>",
    "function"
  ],
  [
    "aureooms-js-fingertree/src/1-digit/4-four.js~four",
    "function/index.html#static-function-Four",
    "<span>Four</span> <span class=\"search-result-import-path\">aureooms-js-fingertree/src/1-digit/4-Four.js</span>",
    "function"
  ],
  [
    "aureooms-js-fingertree/src/4-lazy/0-lazy.js~lazy",
    "function/index.html#static-function-Lazy",
    "<span>Lazy</span> <span class=\"search-result-import-path\">aureooms-js-fingertree/src/4-lazy/0-Lazy.js</span>",
    "function"
  ],
  [
    "aureooms-js-fingertree/src/2-node/2-node2.js~node2",
    "function/index.html#static-function-Node2",
    "<span>Node2</span> <span class=\"search-result-import-path\">aureooms-js-fingertree/src/2-node/2-Node2.js</span>",
    "function"
  ],
  [
    "aureooms-js-fingertree/src/2-node/3-node3.js~node3",
    "function/index.html#static-function-Node3",
    "<span>Node3</span> <span class=\"search-result-import-path\">aureooms-js-fingertree/src/2-node/3-Node3.js</span>",
    "function"
  ],
  [
    "aureooms-js-fingertree/src/1-digit/1-one.js~one",
    "function/index.html#static-function-One",
    "<span>One</span> <span class=\"search-result-import-path\">aureooms-js-fingertree/src/1-digit/1-One.js</span>",
    "function"
  ],
  [
    "aureooms-js-fingertree/src/3-tree/implementations/1-single.js~single",
    "function/index.html#static-function-Single",
    "<span>Single</span> <span class=\"search-result-import-path\">aureooms-js-fingertree/src/3-tree/implementations/1-Single.js</span>",
    "function"
  ],
  [
    "aureooms-js-fingertree/src/0-core/split/split.js~split",
    "function/index.html#static-function-Split",
    "<span>Split</span> <span class=\"search-result-import-path\">aureooms-js-fingertree/src/0-core/split/Split.js</span>",
    "function"
  ],
  [
    "aureooms-js-fingertree/src/1-digit/3-three.js~three",
    "function/index.html#static-function-Three",
    "<span>Three</span> <span class=\"search-result-import-path\">aureooms-js-fingertree/src/1-digit/3-Three.js</span>",
    "function"
  ],
  [
    "aureooms-js-fingertree/src/3-tree/base/tree.js~tree",
    "function/index.html#static-function-Tree",
    "<span>Tree</span> <span class=\"search-result-import-path\">aureooms-js-fingertree/src/3-tree/base/Tree.js</span>",
    "function"
  ],
  [
    "aureooms-js-fingertree/src/1-digit/2-two.js~two",
    "function/index.html#static-function-Two",
    "<span>Two</span> <span class=\"search-result-import-path\">aureooms-js-fingertree/src/1-digit/2-Two.js</span>",
    "function"
  ],
  [
    "aureooms-js-fingertree/src/0-core/_fast/fast-iterators/2-_empty.js~_empty",
    "variable/index.html#static-variable-_EMPTY",
    "<span>_EMPTY</span> <span class=\"search-result-import-path\">aureooms-js-fingertree/src/0-core/_fast/fast-iterators/2-_EMPTY.js</span>",
    "variable"
  ],
  [
    "aureooms-js-fingertree/src/0-core/_fast/fast-iterators/1-_emptygenerator.js~_emptygenerator",
    "function/index.html#static-function-_EmptyGenerator",
    "<span>_EmptyGenerator</span> <span class=\"search-result-import-path\">aureooms-js-fingertree/src/0-core/_fast/fast-iterators/1-_EmptyGenerator.js</span>",
    "function"
  ],
  [
    "aureooms-js-fingertree/src/0-core/_fast/_app3.js~_app3",
    "function/index.html#static-function-_app3",
    "<span>_app3</span> <span class=\"search-result-import-path\">aureooms-js-fingertree/src/0-core/_fast/_app3.js</span>",
    "function"
  ],
  [
    "aureooms-js-fingertree/src/0-core/_fast/_append.js~_append",
    "function/index.html#static-function-_append",
    "<span>_append</span> <span class=\"search-result-import-path\">aureooms-js-fingertree/src/0-core/_fast/_append.js</span>",
    "function"
  ],
  [
    "aureooms-js-fingertree/src/0-core/_fast/_deepl.js~_deepl",
    "function/index.html#static-function-_deepL",
    "<span>_deepL</span> <span class=\"search-result-import-path\">aureooms-js-fingertree/src/0-core/_fast/_deepL.js</span>",
    "function"
  ],
  [
    "aureooms-js-fingertree/src/0-core/_fast/_deepr.js~_deepr",
    "function/index.html#static-function-_deepR",
    "<span>_deepR</span> <span class=\"search-result-import-path\">aureooms-js-fingertree/src/0-core/_fast/_deepR.js</span>",
    "function"
  ],
  [
    "aureooms-js-fingertree/src/0-core/_fast/_digit.js~_digit",
    "function/index.html#static-function-_digit",
    "<span>_digit</span> <span class=\"search-result-import-path\">aureooms-js-fingertree/src/0-core/_fast/_digit.js</span>",
    "function"
  ],
  [
    "aureooms-js-fingertree/src/0-core/_fast/_from_digit.js~_from_digit",
    "function/index.html#static-function-_from_digit",
    "<span>_from_digit</span> <span class=\"search-result-import-path\">aureooms-js-fingertree/src/0-core/_fast/_from_digit.js</span>",
    "function"
  ],
  [
    "aureooms-js-fingertree/src/0-core/_fast/_from_small_list.js~_from_small_list",
    "function/index.html#static-function-_from_small_list",
    "<span>_from_small_list</span> <span class=\"search-result-import-path\">aureooms-js-fingertree/src/0-core/_fast/_from_small_list.js</span>",
    "function"
  ],
  [
    "aureooms-js-fingertree/src/0-core/_fast/_prepend.js~_prepend",
    "function/index.html#static-function-_prepend",
    "<span>_prepend</span> <span class=\"search-result-import-path\">aureooms-js-fingertree/src/0-core/_fast/_prepend.js</span>",
    "function"
  ],
  [
    "aureooms-js-fingertree/src/0-core/concatenate/app3.js~app3",
    "function/index.html#static-function-app3",
    "<span>app3</span> <span class=\"search-result-import-path\">aureooms-js-fingertree/src/0-core/concatenate/app3.js</span>",
    "function"
  ],
  [
    "aureooms-js-fingertree/src/0-core/concatenate/append.js~append",
    "function/index.html#static-function-append",
    "<span>append</span> <span class=\"search-result-import-path\">aureooms-js-fingertree/src/0-core/concatenate/append.js</span>",
    "function"
  ],
  [
    "aureooms-js-fingertree/src/0-core/measure/cache.js~cache",
    "function/index.html#static-function-cache",
    "<span>cache</span> <span class=\"search-result-import-path\">aureooms-js-fingertree/src/0-core/measure/cache.js</span>",
    "function"
  ],
  [
    "aureooms-js-fingertree/src/0-core/split/deepl.js~deepl",
    "function/index.html#static-function-deepL",
    "<span>deepL</span> <span class=\"search-result-import-path\">aureooms-js-fingertree/src/0-core/split/deepL.js</span>",
    "function"
  ],
  [
    "aureooms-js-fingertree/src/0-core/split/deepr.js~deepr",
    "function/index.html#static-function-deepR",
    "<span>deepR</span> <span class=\"search-result-import-path\">aureooms-js-fingertree/src/0-core/split/deepR.js</span>",
    "function"
  ],
  [
    "aureooms-js-fingertree/src/4-lazy/1-delay.js~delay",
    "function/index.html#static-function-delay",
    "<span>delay</span> <span class=\"search-result-import-path\">aureooms-js-fingertree/src/4-lazy/1-delay.js</span>",
    "function"
  ],
  [
    "aureooms-js-fingertree/src/5-api.js~empty",
    "function/index.html#static-function-empty",
    "<span>empty</span> <span class=\"search-result-import-path\">aureooms-js-fingertree/src/5-api.js</span>",
    "function"
  ],
  [
    "aureooms-js-fingertree/src/0-core/concatenate/from.js~from",
    "function/index.html#static-function-from",
    "<span>from</span> <span class=\"search-result-import-path\">aureooms-js-fingertree/src/0-core/concatenate/from.js</span>",
    "function"
  ],
  [
    "aureooms-js-fingertree/src/2-node/2-node2.js~node2",
    "function/index.html#static-function-node2",
    "<span>node2</span> <span class=\"search-result-import-path\">aureooms-js-fingertree/src/2-node/2-Node2.js</span>",
    "function"
  ],
  [
    "aureooms-js-fingertree/src/2-node/3-node3.js~node3",
    "function/index.html#static-function-node3",
    "<span>node3</span> <span class=\"search-result-import-path\">aureooms-js-fingertree/src/2-node/3-Node3.js</span>",
    "function"
  ],
  [
    "aureooms-js-fingertree/src/0-core/concatenate/nodes.js~nodes",
    "function/index.html#static-function-nodes",
    "<span>nodes</span> <span class=\"search-result-import-path\">aureooms-js-fingertree/src/0-core/concatenate/nodes.js</span>",
    "function"
  ],
  [
    "aureooms-js-fingertree/src/0-core/concatenate/prepend.js~prepend",
    "function/index.html#static-function-prepend",
    "<span>prepend</span> <span class=\"search-result-import-path\">aureooms-js-fingertree/src/0-core/concatenate/prepend.js</span>",
    "function"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "https://developer.mozilla.org/en/docs/Web/API/AudioContext",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "https://developer.mozilla.org/en-US/docs/Web/API/DocumentFragment",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "https://developer.mozilla.org/en-US/docs/Web/API/Element",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "https://developer.mozilla.org/en-US/docs/Web/API/Event",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "https://developer.mozilla.org/en-US/docs/Web/API/Node",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "https://developer.mozilla.org/en-US/docs/Web/API/NodeList",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "https://developer.mozilla.org/en/docs/Web/API/XMLHttpRequest",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "src/0-core/_fast/_app3.js",
    "file/src/0-core/_fast/_app3.js.html",
    "src/0-core/_fast/_app3.js",
    "file"
  ],
  [
    "src/0-core/_fast/_append.js",
    "file/src/0-core/_fast/_append.js.html",
    "src/0-core/_fast/_append.js",
    "file"
  ],
  [
    "src/0-core/_fast/_deepl.js",
    "file/src/0-core/_fast/_deepL.js.html",
    "src/0-core/_fast/_deepL.js",
    "file"
  ],
  [
    "src/0-core/_fast/_deepr.js",
    "file/src/0-core/_fast/_deepR.js.html",
    "src/0-core/_fast/_deepR.js",
    "file"
  ],
  [
    "src/0-core/_fast/_digit.js",
    "file/src/0-core/_fast/_digit.js.html",
    "src/0-core/_fast/_digit.js",
    "file"
  ],
  [
    "src/0-core/_fast/_from_digit.js",
    "file/src/0-core/_fast/_from_digit.js.html",
    "src/0-core/_fast/_from_digit.js",
    "file"
  ],
  [
    "src/0-core/_fast/_from_small_list.js",
    "file/src/0-core/_fast/_from_small_list.js.html",
    "src/0-core/_fast/_from_small_list.js",
    "file"
  ],
  [
    "src/0-core/_fast/_prepend.js",
    "file/src/0-core/_fast/_prepend.js.html",
    "src/0-core/_fast/_prepend.js",
    "file"
  ],
  [
    "src/0-core/_fast/fast-iterators/1-_emptygenerator.js",
    "file/src/0-core/_fast/fast-iterators/1-_EmptyGenerator.js.html",
    "src/0-core/_fast/fast-iterators/1-_EmptyGenerator.js",
    "file"
  ],
  [
    "src/0-core/_fast/fast-iterators/2-_empty.js",
    "file/src/0-core/_fast/fast-iterators/2-_EMPTY.js.html",
    "src/0-core/_fast/fast-iterators/2-_EMPTY.js",
    "file"
  ],
  [
    "src/0-core/_fast/fast-iterators/index.js",
    "file/src/0-core/_fast/fast-iterators/index.js.html",
    "src/0-core/_fast/fast-iterators/index.js",
    "file"
  ],
  [
    "src/0-core/_fast/index.js",
    "file/src/0-core/_fast/index.js.html",
    "src/0-core/_fast/index.js",
    "file"
  ],
  [
    "src/0-core/concatenate/app3.js",
    "file/src/0-core/concatenate/app3.js.html",
    "src/0-core/concatenate/app3.js",
    "file"
  ],
  [
    "src/0-core/concatenate/append.js",
    "file/src/0-core/concatenate/append.js.html",
    "src/0-core/concatenate/append.js",
    "file"
  ],
  [
    "src/0-core/concatenate/from.js",
    "file/src/0-core/concatenate/from.js.html",
    "src/0-core/concatenate/from.js",
    "file"
  ],
  [
    "src/0-core/concatenate/index.js",
    "file/src/0-core/concatenate/index.js.html",
    "src/0-core/concatenate/index.js",
    "file"
  ],
  [
    "src/0-core/concatenate/nodes.js",
    "file/src/0-core/concatenate/nodes.js.html",
    "src/0-core/concatenate/nodes.js",
    "file"
  ],
  [
    "src/0-core/concatenate/prepend.js",
    "file/src/0-core/concatenate/prepend.js.html",
    "src/0-core/concatenate/prepend.js",
    "file"
  ],
  [
    "src/0-core/index.js",
    "file/src/0-core/index.js.html",
    "src/0-core/index.js",
    "file"
  ],
  [
    "src/0-core/measure/cachedmeasure.js",
    "file/src/0-core/measure/CachedMeasure.js.html",
    "src/0-core/measure/CachedMeasure.js",
    "file"
  ],
  [
    "src/0-core/measure/cache.js",
    "file/src/0-core/measure/cache.js.html",
    "src/0-core/measure/cache.js",
    "file"
  ],
  [
    "src/0-core/measure/index.js",
    "file/src/0-core/measure/index.js.html",
    "src/0-core/measure/index.js",
    "file"
  ],
  [
    "src/0-core/split/split.js",
    "file/src/0-core/split/Split.js.html",
    "src/0-core/split/Split.js",
    "file"
  ],
  [
    "src/0-core/split/deepl.js",
    "file/src/0-core/split/deepL.js.html",
    "src/0-core/split/deepL.js",
    "file"
  ],
  [
    "src/0-core/split/deepr.js",
    "file/src/0-core/split/deepR.js.html",
    "src/0-core/split/deepR.js",
    "file"
  ],
  [
    "src/0-core/split/index.js",
    "file/src/0-core/split/index.js.html",
    "src/0-core/split/index.js",
    "file"
  ],
  [
    "src/1-digit/0-digit.js",
    "file/src/1-digit/0-Digit.js.html",
    "src/1-digit/0-Digit.js",
    "file"
  ],
  [
    "src/1-digit/1-one.js",
    "file/src/1-digit/1-One.js.html",
    "src/1-digit/1-One.js",
    "file"
  ],
  [
    "src/1-digit/2-two.js",
    "file/src/1-digit/2-Two.js.html",
    "src/1-digit/2-Two.js",
    "file"
  ],
  [
    "src/1-digit/3-three.js",
    "file/src/1-digit/3-Three.js.html",
    "src/1-digit/3-Three.js",
    "file"
  ],
  [
    "src/1-digit/4-four.js",
    "file/src/1-digit/4-Four.js.html",
    "src/1-digit/4-Four.js",
    "file"
  ],
  [
    "src/1-digit/index.js",
    "file/src/1-digit/index.js.html",
    "src/1-digit/index.js",
    "file"
  ],
  [
    "src/2-node/2-node2.js",
    "file/src/2-node/2-Node2.js.html",
    "src/2-node/2-Node2.js",
    "file"
  ],
  [
    "src/2-node/3-node3.js",
    "file/src/2-node/3-Node3.js.html",
    "src/2-node/3-Node3.js",
    "file"
  ],
  [
    "src/2-node/index.js",
    "file/src/2-node/index.js.html",
    "src/2-node/index.js",
    "file"
  ],
  [
    "src/3-tree/base/tree.js",
    "file/src/3-tree/base/Tree.js.html",
    "src/3-tree/base/Tree.js",
    "file"
  ],
  [
    "src/3-tree/base/index.js",
    "file/src/3-tree/base/index.js.html",
    "src/3-tree/base/index.js",
    "file"
  ],
  [
    "src/3-tree/implementations/0-empty.js",
    "file/src/3-tree/implementations/0-Empty.js.html",
    "src/3-tree/implementations/0-Empty.js",
    "file"
  ],
  [
    "src/3-tree/implementations/1-single.js",
    "file/src/3-tree/implementations/1-Single.js.html",
    "src/3-tree/implementations/1-Single.js",
    "file"
  ],
  [
    "src/3-tree/implementations/2-deep.js",
    "file/src/3-tree/implementations/2-Deep.js.html",
    "src/3-tree/implementations/2-Deep.js",
    "file"
  ],
  [
    "src/3-tree/implementations/index.js",
    "file/src/3-tree/implementations/index.js.html",
    "src/3-tree/implementations/index.js",
    "file"
  ],
  [
    "src/3-tree/index.js",
    "file/src/3-tree/index.js.html",
    "src/3-tree/index.js",
    "file"
  ],
  [
    "src/4-lazy/0-lazy.js",
    "file/src/4-lazy/0-Lazy.js.html",
    "src/4-lazy/0-Lazy.js",
    "file"
  ],
  [
    "src/4-lazy/1-delay.js",
    "file/src/4-lazy/1-delay.js.html",
    "src/4-lazy/1-delay.js",
    "file"
  ],
  [
    "src/4-lazy/index.js",
    "file/src/4-lazy/index.js.html",
    "src/4-lazy/index.js",
    "file"
  ],
  [
    "src/5-api.js",
    "file/src/5-api.js.html",
    "src/5-api.js",
    "file"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ]
]